const addon = require("./tfhe_comparison.node");
const vec = addon.getkeys();
const clientkey = vec[0];
const serverkey = vec[1];
const publickey = vec[2];
const enc_a = addon.enc(1743242617, clientkey);
const enc_b = addon.encpub(-2200565386, publickey);
const enc_comp = addon.gt(enc_a, enc_b, serverkey);
const dec_comp = addon.dec(enc_comp, clientkey);
console.log(dec_comp);