const addon = require("./tfhe_comparison.node");
const vec = addon.getkeys();
const clientkey = vec[0];
const serverkey = vec[1];
const pubkey = addon.getpublickey(clientkey);
const enc_a = addon.enc(1743242636, clientkey);
const enc_b = addon.encpub(1743242617, pubkey);
const enc_comp = addon.compare(enc_a, enc_b, serverkey);
const dec_comp = addon.dec(enc_comp, clientkey);
console.log(dec_comp);