/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * module registration is done by the runtime, no need to explicitly do it now.
 * run $napi build
 */
export declare function gt(clearA: number, clearB: number): boolean
export declare function getclientkey(): Buffer
export declare function getserverkey(clientKeyBuf: Buffer): Buffer
export declare function enc(clearA: number, clientKeyBuf: Buffer): number
